name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Check Clang++ Version
        run: clang++ --version

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Cache CMake build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Clean Build Directory
        run: |
          rm -rf build
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=20
          ctest --test-dir build/release --output-on-failure

      - name: Check for Errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Build or tests failed!"
            exit 1
          fi
